# Generated by Django 3.1.5 on 2023-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('gst', models.IntegerField(default=0)),
            ],
        ),
    ]
