# Generated by Django 3.1.5 on 2023-08-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salevoucherapp', '0008_auto_20230803_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='add_prod',
            new_name='add_prod_id',
        ),
    ]
